### PR TITLE
Add wishlist and prio read access

### LINKED ISSUE #55: Allow wishlists and priority lists to be hidden from raiders.
Several people have requested this change.

### PR DESCRIPTION
**Pull request by Lemmings19**
fixes #55 
resolves #55 
closes #55

### CODE REVIEW

**Comment by Lemmings19** [comment]
New checkboxes in the guild settings page:
image

New checks in the audit log page:
image

Roster, character, and item list pages will now omit wishlist and prio sections for users who aren't allowed to see them based on the settings.

**Review by nilithu — APPROVED** [review]

**Review by nilithu — APPROVED** [review]

**Review by nilithu — APPROVED** [review]

**Review by nilithu — CHANGES_REQUESTED** [review]
shouldn't the migration also update the existing values in the database?

**Review by nilithu — APPROVED** [review]

**Review by nilithu — APPROVED** [review]

**Comment by Lemmings19** [comment]
@nilithu I'm going to manually run a few SQL statements to update the production data after backing it up. I would really like to automate the process, as doing it manually every time we add new permissions is risky.

**Comment by nilithu** [comment]
> 
> 
> @nilithu I'm going to manually run a few SQL statements to update the production data after backing it up. I would really like to automate the process, as doing it manually every time we add new permissions is risky.

then everything should be ready for a merge. Need to think about how to improve that workflow in the future :)

**Comment by Lemmings19** [comment]
Indeed.

**Pull request merged**
